import { FormBuilder, Validators } from '@angular/forms';

export function addStage1FormControls(fb: FormBuilder): Record<string, unknown> {
  return {
    organizationType: ['', Validators.required],
    nominationLetterAttached: [''],
    ndaEngagementDescription: [''],
    consultationCountry: [''],
    consultationContactPerson: [''],
    consultationMode: [''],
    consultationDates: [''],
    ndaInstitution: [''],
    ndaContactPerson: [''],
    ndaContactInfo: [''],
    consultationSummary: [''],
    applicantName: ['', Validators.required],
    applicantAcronym: ['', Validators.required],
    legalAddress: ['', Validators.required],
    operationalAddress: [''],
    website: ['', Validators.required],
    primaryContactName: ['', Validators.required],
    primaryContactEmail: ['', [Validators.required, Validators.email]],
    primaryContactPhone: ['', Validators.required],
    secondaryContactName: [''],
    secondaryContactEmail: ['', Validators.email],
    secondaryContactPhone: [''],
    scopeOfOperations: ['', Validators.required],
    scopeOfOperationsOther: [''],
    typeOfEntity: ['', Validators.required],
    typeOfEntityOther: [''],
    areaOfOperation: fb.group({
      developingCountries: [false],
      leastDevelopedCountries: [false],
      smallIslandDevelopingStates: [false],
      developedCountries: [false],
    }),
    headquartersCountry: ['', Validators.required],
    incorporationCountry: ['', Validators.required],
    hasLegalPersonality: ['', Validators.required],
    hasLegalCapacity: ['', Validators.required],
    canReceiveFundsDirectly: ['', Validators.required],
    canHandleGCFCurrencies: ['', Validators.required],
    canMaintainInterestBearingAccount: ['', Validators.required],
    canUndertakeFullCycle: ['', Validators.required],
    fullCycleDescription: [''],
    hasFiduciaryCapacity: ['', Validators.required],
    hasESSCapacity: ['', Validators.required],
    hasGenderCapacity: ['', Validators.required],
    hasMonitoringCapacity: ['', Validators.required],
    businessMandate: ['', Validators.required],
    hasClimateFinanceExperience: [''],
    climateFinanceOverview: [''],
    hasTrackRecordInRegion: [''],
    trackRecordOverview: [''],
    fiduciaryLevel: ['', Validators.required],
    projectManagementLevel: ['', Validators.required],
    essLevel: ['', Validators.required],
    hasGrievanceMechanism: ['', Validators.required],
    grievanceMechanismLevel: [''],
    genderLevel: ['', Validators.required],
    monitoringLevel: ['', Validators.required],
    canEnsureDownstreamCompliance: ['', Validators.required],
    canMonitorCompliance: ['', Validators.required],
    accreditedByGEF: [false],
    accreditedByAF: [false],
    accreditedByEUDGINTPA: [false],
    fastTrackComplianceDetails: [''],
    hasReceivedReadinessSupport: ['', Validators.required],
    hasServedAsExecutingEntity: ['', Validators.required],
    executingEntityDetails: [''],
    hasServedAsDeliveryPartner: ['', Validators.required],
    hasEngagedInPSAA: ['', Validators.required],
    preparedForPartnerships: ['', Validators.required],
  };
}
